[Game]
host = "localhost"
input_port = 43211
output_port = 43210

[InputLayer]
multicast_ip = "224.5.23.2"
game_controller_ip = "224.5.23.1"
vision_port = 10006
autoref_port = 10010
game_controller_port = 10003
use_ref_vision = true
side = "right"

[Tracking]
color = "yellow"

[Decision]
coach = "SimpleCoach"

[Control]
planner = "VOPlanner"

[OutputLayer]
host_ip = "localhost"
command_port = 20011
serial_port = "/dev/ttyUSB0"
baud_rate =  115200
use_gr_sim = true
